name       : numix-icon-theme-circle
version    : 23.07.08
release    : 42
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/23.07.08.tar.gz : 4fc1a7c6139a4214de10016935ca80fa5eef0eb4e2e8637baf0fe9d4938a4923
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
