name       : numix-icon-theme-circle
version    : 18.04.04
release    : 13
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/18-04-04.tar.gz : 68967ce31d40c7f9f1adda61a560edca0e63039244fe8799f70570186cafc036
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
