name       : numix-icon-theme-circle
version    : 22.02.06
release    : 31
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/22.02.06.tar.gz : 605121b8427b06f77faa4cbafb395400a0b6d464f1a168cd3fc866b6a9a6ca66
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
