name       : numix-icon-theme-circle
version    : 19.04.15
release    : 21
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/19.04.15.tar.gz : 931c4b633db40e5eee3ba2fe1827c3db1a08f2233b1bd4d05b9c2e8998d73ff3
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
