name       : numix-icon-theme-circle
version    : 23.09.11
release    : 43
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/23.09.11.tar.gz : 89c4345380900213c098c94a2115ee87e4dbecb2b30772222331c20109b50140
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
