name       : numix-icon-theme-circle
version    : 22.08.15
release    : 35
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/22.08.15.tar.gz : 56d7cc34c3b8b3af33059883d02634a57b184a2798544fd5726de733cb17f840
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
