name       : numix-icon-theme-circle
version    : 17.04.05
release    : 9
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/17-04-05.tar.gz : d277ba6af1fc77f0ecd3912c3ac82114c84ed860b953ec94bb69b49c58585c8f
homepage   : http://numixproject.org/
license    : GPL-3.0
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
