name       : numix-icon-theme-circle
version    : 22.06.14
release    : 34
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/22.06.14.tar.gz : ca6b30d1e8b08f70c5437b4762a2fb9d6d1878ce3179ed8610a95b3f44cf4cc0
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
