name        : numix-icon-theme-circle
version     : 0.2.20150716.1646
release     : 6
source      :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-icon-theme-circle/numix-icon-theme-circle_1.0.2+4~201507161646~ubuntu14.04.1.tar.gz : 69b37dabae406bb4fecb8511b45649fdc8738381716af6b400cee772d4b9bdf8
homepage    : http://numixproject.org/
license     :
    - GPLv3+
summary     : Numix Circle Icon Theme
description : |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
