name       : numix-icon-theme-circle
version    : 19.05.07
release    : 22
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/19.05.07.tar.gz : 7ed94d7618f427847f264fda1a77672d18790339cfd125e030f282549d1047f3
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
