name       : numix-icon-theme-circle
version    : 19.09.20
release    : 23
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/19.09.20.tar.gz : 1039c6a82db0b092eb49dec78d36718c1c0d739dd0e0a17ba9768724666e86af
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
