name       : numix-icon-theme-circle
version    : 19.02.07
release    : 18
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/19.02.07.tar.gz : 64ea91d809ea7918dc180e8f4eeeda96099ba1e7c15d46aa2b565b1f85a91ca3
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
