name       : numix-icon-theme-circle
version    : 16.08.31
release    : 7
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/16-08-31.tar.gz : b9b1dc394b9c5bda002cdfdaccbc2dd6c9df76a3b4ac8fe8657d850b9ecdf55d
homepage   : http://numixproject.org/
license    : GPL-3.0
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
