name       : numix-icon-theme-circle
version    : 19.03.20
release    : 20
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/19.03.20.tar.gz : 63f01f0401a11ae715df12c9dd8200e287cd52e7e4c01223707baf8e40d73d47
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
