name       : numix-icon-theme-circle
version    : 18.02.16
release    : 12
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/18-02-16.tar.gz : 813981cfeefefa0a61530b079f9109d7fddf66b2780c1468a6e7262257ba04aa
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
