name        : numix-icon-theme-circle
version     : 0.2.20150207.1452
release     : 4
source      :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-icon-theme-circle/numix-icon-theme-circle_1.0.2+3~201502071452~ubuntu15.04.1.tar.xz : e14fb42ce436bf4dafd0384bb1bf64e186ea8edcea7a65675db4ef59a2dec9f0
homepage    : http://numixproject.org/
license     :
    - GPLv3+
summary     : Numix Circle Icon Theme
description : |
    Numix Circle is an icon theme from the Numix project
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
