name       : numix-icon-theme-circle
version    : 16.11.09
release    : 8
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/16-11-09.tar.gz : 7de05e28e4330adeace4e5212e20d3332ef786b3d687ec31d1f3873fdb30a200
homepage   : http://numixproject.org/
license    : GPL-3.0
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
