name       : numix-icon-theme-circle
version    : 19.02.22
release    : 19
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/19.02.22.tar.gz : 4d35ae04049f7e072bde2fc4ec1f44efcade0efb8ef8af3afaee5613a5d5ff8d
homepage   : http://numixproject.org/
license    : GPL-3.0-or-later
component  : dekstop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mv Numix-Circle %installroot%/usr/share/icons/
    mv Numix-Circle-Light %installroot%/usr/share/icons/
