name       : numix-icon-theme-circle
version    : 23.05.15
release    : 40
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/23.05.15.tar.gz : 9e337d0b2d428b61bec63cf9a5064fef5f93f93f613569514d117c2deb682fc5
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
