name       : numix-icon-theme-circle
version    : 21.10.16
release    : 29
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/21.10.16.tar.gz : dd69336a794a184d9b58137a18e079988611929d679c4720e00f989c6b58d845
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
